### ISSUE TITLE
Initial Migration: Cannot add foreign key constraint 

### ISSUE THREAD

**Issue by tok3** [leskhq/Laravel-Enterprise-Starter-Kit#1]
[PDOException]  
SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint 

Fix: Change line 21, set permission_id nullable
old:  $table->integer('permission_id')->unsigned()->default(0);
new:  $table->unsignedInteger('permission_id')->nullable()->default(0);

**Comment by joaosalless** [comment]
+1

**Comment by sroutier** [comment]
Done thanks.
