### ISSUE TITLE
Branch L55 created

### ISSUE THREAD

**Issue by sroutier** [leskhq/Laravel-Enterprise-Starter-Kit#100]
Hello all,

Just a quick note to let you know that a new branch L55 was created to allow us to start working together on upgrading LESK to Laravel 5.5.

Also created a Gitter room so that we can all chat.
https://gitter.im/LESK-DEV/Lobby

Cheers.
/S

**Comment by rap2hpoutre** [comment]
Hi. What about 5.6?

**Comment by sroutier** [comment]
Hello @rap2hpoutre, unfortunately 5.6 is not a target for LESK. Being an enterprise project the focus in on LTS releases. That being said using Laravel 5.6 as a base should not too hard as it really close to 5.5.

**Comment by rap2hpoutre** [comment]
Ok thanks!
