### ISSUE TITLE
open-to-all permission only works for home page & faust

### ISSUE THREAD

**Issue by tamer-hassan** [leskhq/Laravel-Enterprise-Starter-Kit#11]
Hi,

according to the documentation: "A route assigned the permission open-to-all will be authorize for all users, authenticated or not."

However, upon testing, this seems to only work on the home page (home or backslash) and faust. It doesn't make a difference whether the route is defined within the "authorize" middleware route group or outside it.
This while keeping in mind issue #10 , for example, having made sure "acl-test/open-to-all" route is assigned the permission "open-to-all" from the admin interface. But I'm always being redirected to auth/login whenever I visit open-to-all route.

BR

**Comment by sroutier** [comment]
Hummmm.... Are you sure. I have just double checked and it looks to be working fine on my end. I appreciate your help looking into this as the security aspect is crucial.

The Laravel routes "home", "backslash" and "faust" are not protected by the authorize middleware.

Is there anything in your logs files?
Are you sure that you have configured your Laravel routes.php file properly?

Here are the general steps required to define a new route protected by the authorize middleware. They will probably appear obvious to you as I am sure that you figured out most of this already, but let me know if you find it well explained and I will try to include them in the documentation. I have to rewrite the documentation as the README is really getting massive and perhaps a little confusing.

1) Define new Laravel route in 'app/Http/routes.php', make sure to define such route inside a "Route::Group(...)" segment to invoke the authorize middleware.
2) Build or code required view and controller.
3) Login as root or any user with the required permissions.
4) Define application route for the new Laravel route defined in step 1. This can be done on the page "Admin | Routes" located at http://<server>/admin/routes. The second button on the toolbar, 2 arrows pointing to each other and forming a circle, will load all missing routes automatically.
5) From the "Admin | Routes" page, assign a permission to the new route, by selecting the desired permission in the dropdown select in front of the new route. Save the assignment by clicking on the floppy disk icon on the toolbar. 
6) Test it with multiple users having various roles and permissions.

Below you can see that I have set both route "acl-test/open-to-all" and "acl-test/power-users" to require the "Open to all" permission.
![screen shot 2016-01-06 at 12 22 21 pm](https://cloud.githubusercontent.com/assets/3011606/12149819/d2c69a4e-b473-11e5-98e2-c74d197ad460.png)

Here is the "acl-test/power-users" page seen as an un-authenticated or guest user:
![screen shot 2016-01-06 at 12 22 56 pm](https://cloud.githubusercontent.com/assets/3011606/12149923/7ee4df16-b474-11e5-9f5e-99638b17b385.png)

Here is the same "acl-test/power-users" page seen as an authenticated user.
![screen shot 2016-01-06 at 12 23 22 pm](https://cloud.githubusercontent.com/assets/3011606/12149963/b1d43034-b474-11e5-8640-d9c2bc4efac4.png)

Here is the "acl-test/open-to-all" page seen as a guest user.
![screen shot 2016-01-06 at 12 25 52 pm](https://cloud.githubusercontent.com/assets/3011606/12149990/d5b3de00-b474-11e5-8c8e-4250e336f96a.png)

Finally the "acl-test/open-to-all" page seen as an authenticated user.
![screen shot 2016-01-06 at 12 25 14 pm](https://cloud.githubusercontent.com/assets/3011606/12150001/e348dab6-b474-11e5-984f-43372391b4ea.png)

Question: Why are you being redirected to the "auth/login" each time? You should be getting the Error 403 page, as shown below after I reset the "acl-test/power-users" to either a permission that the user does not have or "blank" to unset the permission... 
See: 
![screen shot 2016-01-06 at 1 05 04 pm](https://cloud.githubusercontent.com/assets/3011606/12150166/2cb746f0-b476-11e5-9b23-05a9bdf86e14.png)

I need to think about this a little...

**Comment by sroutier** [comment]
Silly question: Can you make sure that the user that you are testing this with is enabled?
With a disabled user you would get redirected to the "auth/login" page instead of getting the error 403.

Thanks.
/S

**Comment by sroutier** [comment]
One more idea! Is the walled garden mode enabled?

**Comment by tamer-hassan** [comment]
You nailed it.. Walled Garden mode is in fact enabled. You saved me from pulling my hair out!

**Comment by sroutier** [comment]
Cool! Glad the mystery is explained. I already have TODO note in the Walled Garden middleware to take a list of route that will be exempt from the configuration, that would allow you to specify a few pages that you want accessible to all.

Cheers.
/Seb

**Comment by sroutier** [comment]
Closed by 5dbbdf82b28a0670a7b068312988cad4d5d79b2b.
Walled Garden now takes exemption paths from config file.
