### ISSUE TITLE
Error when Running php artisan make:module:model

### ISSUE THREAD

**Issue by makelued21** [leskhq/Laravel-Enterprise-Starter-Kit#117]
Command "make:module:model" is not defined.Did you mean one of these?    make:module:controller    make:module:migration    make:module    make:module:request    make:model    ide-helper:models

what when wrong?

**Comment by sroutier** [comment]
Hello @makelued21,

You are right currently there is no ```make:module:model``` command. Perhaps it can be added for the next version.

Thanks for pointing it out.
/s
