### ISSUE TITLE
Any functionality for email?

### ISSUE THREAD

**Issue by imkevinabraham** [leskhq/Laravel-Enterprise-Starter-Kit#12]
L51ESK handles all auth, Is there any functionality built in to handle things like:
- Confirmation emails?
- Password reminder emails?

**Comment by sroutier** [comment]
Hello Kevin,

Thanks for checking things up. 

By default the Laravel framework provides for your question about "Password reminders" but it will not send the user it's current password as that would be very insecure. Instead it generate a password reset token and emails that to the user.

As for your question about "confirmation emails", I have not implemented it yet. But I will make sure to add it to the list.

Thanks.
/s

**Comment by imkevinabraham** [comment]
Thanks S, That would be awesome. I've been playing with your package and so far its been great. Only thing I really noticed missing was that confirmation email functionality out of the box.

**Comment by tamer-hassan** [comment]
Hi Kevin,
For "Forgot Password" functionality, Bill Keck has recently written a good guide on his blog:
[Setting Up a Forgot Password Form and Controller in Laravel 5.1](https://laraveltips.wordpress.com/category/forgot-password-form-and-controller/)

Shouldn't be hard to integrate with this project, I think.

**Comment by tamer-hassan** [comment]
And a more complete solution here:
https://github.com/jeremykenedy/laravel-auth
Laravel 5.1 with user authentication, registration with email confirmation, social media authentication, password recovery, and captcha

**Comment by imkevinabraham** [comment]
Thanks @thassan I've managed to integrate forgot password into this package.
Also the complete solution looks really interesting, I'll have to clone and check it out.

**Comment by sroutier** [comment]
Finally got around to implement some email functions.
/s
