### ISSUE TITLE
dynamic breadcrumbs implementation for ideas

### ISSUE THREAD

**Issue by tamer-hassan** [leskhq/Laravel-Enterprise-Starter-Kit#16]
Dear Sebastian,

Just thought if you took a look at this it would be of some help, at least in terms of dynamic breadcrumbs, since it's already implemented. Why reinvent the entire wheel, right? :)

https://github.com/jeremykenedy/laravel-admin

**Comment by sroutier** [comment]
Hello Tamer,

Thanks for the pointer, I will have a look at it. I am almost done, just need to clean up the code and test it.

/s
