### ISSUE TITLE
user passwords not working after update

### ISSUE THREAD

**Issue by sloan58** [leskhq/Laravel-Enterprise-Starter-Kit#17]
First of all, thanks for the awesome starter kit.  I'm loving it!

I've found that when I update a users roles, the users password does not work on the next login.  I think it's due to an empty 'password' attribute from the form being applied on the $user->update() method.  I've added a Hash::check if/else in the UsersController@update to check if the password has changed or is blank.  I might be be missing something, but thought this might be an issue that needs to be addressed.

**Comment by tamer-hassan** [comment]
confirmed. I had the same issue when adding a role to a user. the password gets blanked out indeed when submitting the form with the new role added.

**Comment by sroutier** [comment]
Sorry about this guys. I have already fixed it on my server!
I will patch it asap with a new dynamic menu feature.
/s

**Comment by tamer-hassan** [comment]
@sroutier Hope all is well with you. It's been 12 days. Something must've been keeping you very busy. What have you been up to? :)

**Comment by sroutier** [comment]
LOL! Sorry @thassan. I have worked a little on the project but not as much as I would have liked. Mostly worked on helping my sister move and painting her new house. Thanks for the nudge. I'll get back on it asap!
