### ISSUE TITLE
User based permissions

### ISSUE THREAD

**Issue by PrimozRome** [leskhq/Laravel-Enterprise-Starter-Kit#2]
Is there a plan to support also user-based permissions and not only role-based permissions?

**Comment by sroutier** [comment]
It's totally doable, but I have mixed feelings about this one.
On one hand, I like options and I believe in giving people all the ropes they need to hang themselves. On the other hand, best practice in the authorization world tends to prevent people & administrators from doing that. The general feeling is that in the long term, it is usually much easier to manage role and group permissions rather then allowing the assignment of permissions to users.

I would be curious to find out why you need user-based permissions? What use case do you have that cannot be answered by a strict role-based permission system? Or what use case could be done with roles but not having user-based permissions makes it just that much harder?

**Comment by PrimozRome** [comment]
Thanks for having this discussion and I value your input on the subject. In our company we have developed an intranet PHP application that handles entire company process, from ordering, production, R&D, material and stock management to financial part, invoicing, forecasting and so on. 

Our app was designed with users, roles and user-based permission model. We could answer everything with a role-based permission model but because the app is complex and a lot of different people (profiles) are using it, we would need a lot of different roles to cover every scenario. And that seemed awkward at the time we started to develop it. We opted for user-based permissions. There are cases that we are adding new functionality to the app (and permissions to access it) on the go and only a certain employee needed permissions for that. In the role-based permission system I would need to create a new role, grant new permissions to that role and then apply the role to the user. Now I only create new permissions and assign them to the right users. 

I do not know any good practices that role-based permission system is better. Would love to read more about this... 

I am looking to rewrite the app in Laravel 5.1 and came across this starter kit which I intend to test. Could be a good starting point for the rewrite. Since currently we use user-based permission, my question was targeting toward this, because I am looking to make migration as less painful as possible if it happens.

**Comment by sroutier** [comment]
Hello,

It's not for me to pass judgement on your design and procedures, I will just warn you against using a user-based permission system, they tend to be an administration nightmare. I am having a major déjà vu here. We have just been over this at my primary employer. The main driving force behind this project is, like for you, the upgrade of a legacy system to a new and modern platform, and the design of a second and unrelated Web application. Long story short: 35,000 people, 12,000 to 16,000 active at any one time, all over the world. People change department/group and location a lot. We do not want to manually manage that. 

Here are some articles that we based our design on:
Quick intro: https://en.wikipedia.org/wiki/Role-based_access_control
Role-Based Security: Pros, Cons & Some Research Directions: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.31.3593&rep=rep1&type=pdf
Role-Based Access Control: The NIST Solution: http://www.sans.org/reading-room/whitepapers/sysadmin/role-based-access-control-nist-solution-1270
Don’t Do Role-Based Authorization Checks; Do Activity-Based Checks: https://lostechies.com/derickbailey/2011/05/24/dont-do-role-based-authorization-checks-do-activity-based-checks/

With either role-based or activity-based permission system, combined with LDAP/AD integration and enabling both `LDAP_REPLICATE_GROUP_MEMBERSHIP` and `LDAP_RESYNC_ON_LOGIN` we get it all for free! When a person is moved to different groups, in LDAP/AD, they automatically get assign new roles (they old roles get revoked) in the Web application and therefore new permissions that match their new responsibilities. The trick is to properly plan the mapping between roles and permissions.

That being said, you know your environment better than anyone else, and if user-based permissions is what you need, I have no objections. I will put it in the road map and get to it soon. Just got a couple other things to finish first.

Don't hesitate to ping me if you have any other questions as you explore.

Cheers.
/s

**Comment by sroutier** [comment]
Hey there,

Just completed the user-based permission feature. Please give it a try when you have some time.
Let me know if you have any questions.

Cheers.
/s
