### ISSUE TITLE
Menus not worked with PostgreSQL

### ISSUE THREAD

**Issue by KrasilnikovKB** [leskhq/Laravel-Enterprise-Starter-Kit#21]
Clean installation:

git clone https://github.com/sroutier/laravel-5.1-enterprise-starter-kit.git l51esk
composer install
npm install
cp .env.example .env
edit .env and config/database.php  (connect do PGSQL)
./artisan key:generate
chmod -R ugo+rw storage/
chmod -R ugo+rw bootstrap/cache/
./artisan migrate
./artisan db:seed

... first login root-Password1 and get :
![image](https://cloud.githubusercontent.com/assets/16627494/12912179/03f5ab9a-cf28-11e5-89e1-5b5ff9080f00.png)

go to dashboard :

![image](https://cloud.githubusercontent.com/assets/16627494/12912213/34c0b1e8-cf28-11e5-9288-75af7dc4b286.png)

at log-file get error:

![image](https://cloud.githubusercontent.com/assets/16627494/12912346/ee5e7ec8-cf28-11e5-9569-060aa0c7ec55.png)

.../storage/logs# cat ./laravel.log
ERROR:  invalid input syntax for integer: \"root\" (SQL: select \* from \"menus\" where \"menus\".\"id\" = root limit 1) at ...../vendor/laravel/framework/src/Illuminate/Database/Connection.php:651, PDOException(code: 22P02): SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: \"root\" at .../vendor/laravel/framework/src/Illuminate/Database/Connection.php:321)"}

if change DB on mysql all fine work:

![image](https://cloud.githubusercontent.com/assets/16627494/12912280/837ca95e-cf28-11e5-933b-bd15ad1b0033.png)

**Comment by sroutier** [comment]
Well that is not good! Sorry about this.
Let me spin up a PostgreSQL server and take a look.
Thanks for the detailed report, that always helps.
/s

**Comment by sroutier** [comment]
Should be fixed. Please give it a try and let me know.
Good catch, I appreciate the help.
Thank you.
/S
