### ISSUE TITLE
Can't create new menu item

### ISSUE THREAD

**Issue by KrasilnikovKB** [leskhq/Laravel-Enterprise-Starter-Kit#22]
Logged as root.

Try rename menu item : 

![image](https://cloud.githubusercontent.com/assets/16627494/12920484/e016d1ea-cf59-11e5-8240-526dd6f3bdcc.png)

press SAVE and get error :

![image](https://cloud.githubusercontent.com/assets/16627494/12920539/125f8d9a-cf5a-11e5-8609-c8e2bdf00930.png)

but new menu items sucessfully created

P.S. Sorry for my english and many questions

**Comment by sroutier** [comment]
Aye!!! I am sure I tested this... Let me look into it.
/s

**Comment by sroutier** [comment]
Sorry about this, looks like I crossed my streams...
Forgot to merge one function...
