### ISSUE TITLE
Update menu item under PostgreSQL

### ISSUE THREAD

**Issue by KrasilnikovKB** [leskhq/Laravel-Enterprise-Starter-Kit#23]
Hi

I returned to PostgreSQL

and here again is not working menu update (((

![image](https://cloud.githubusercontent.com/assets/16627494/12970112/62425b3e-d09b-11e5-8411-35c41b4ef89c.png)

press SAVE and get error:

![image](https://cloud.githubusercontent.com/assets/16627494/12970305/074376f2-d09e-11e5-936d-36d6c3f10675.png)

**Comment by sroutier** [comment]
Fixed! Sorry about that.
Once more good catch, I was using the wrong column name in the validation rule.

/s
