### ISSUE TITLE
Menu doesn't expand on pageload

### ISSUE THREAD

**Issue by primeinc** [leskhq/Laravel-Enterprise-Starter-Kit#24]
If for example you click on the `Audit` page, after it loads the `Admin` menu group will be collapsed, I'd expect it to stay open.

As a temporary workaround, I changed `$MENU_GROUP_START` to always include the `active` class, but obviously that isn't ideal.

``` php
public $MENU_GROUP_START    = "<li class='treeview active'><a href='@URL@'><i class='@ICON@'></i><span>@LABEL@</span><i class='fa fa-angle-left pull-right'></i></a><ul class='treeview-menu'>";
```

`app/Handlers/L51ESKSecuredMenuHandler.php Line 37`

**Comment by sroutier** [comment]
Hello,

You are right, the menu does not maintain it's state when the page reloads. It would be nice but I have not yet found a nice way to resolve that issue. We have a few options, just need to analyse the pros and cons and get it done.
I will try to tackle this soon.

/s
