### ISSUE TITLE
What for setPasswordAttribute in User Model?

### ISSUE THREAD

**Issue by sugengsuprayogi** [leskhq/Laravel-Enterprise-Starter-Kit#27]
What for setPasswordAttribute in User Model?

Because user register can't relogin after register.

**Comment by r4lly99** [comment]
hi sugeng , i try to answer you question, i think that setter for password , so when password being saved to the database , it's converted to encrypted text to secure it's value from db admin. Your second question maybe because you forgot the password itself.

**Comment by sugengsuprayogi** [comment]
@r4lly99 this mutator for password use for database seeder,  the user can't log in after register and enabled by admin

**Comment by sroutier** [comment]
Thanks for the tip @sugengsuprayogi. You were totally correct.
/s
