### ISSUE TITLE
preg_match(): No ending delimiter '.' found

### ISSUE THREAD

**Issue by namnh8x** [leskhq/Laravel-Enterprise-Starter-Kit#28]
Hi,

When I ran './artisan db:seed' I got the error:

`[ErrorException]                             
preg_match(): No ending delimiter '.' found`

What should I do in this case, because there are a lot of regex parts in the project to check.

Thank you!

**Comment by sroutier** [comment]
Thanks for the note.
I left an old RegEx malformed in the DB seeder.
Let me know if you have any other issues.
/s
