### ISSUE TITLE
Unable to change root password

### ISSUE THREAD

**Issue by losttheplot** [leskhq/Laravel-Enterprise-Starter-Kit#29]
Thanks for making this starter kit available. I'm new to Lavarel so forgive me if I'm missing something obvious, but how does one change the root password as root without modifying line 122 of /app/User.php to something like the following?

```
        // Protect the root user from edits.
        if ('root' == $this->username && Auth::user()->id != $this->id) {
            return false;
        }
```

And if the root user record is opened up for potential changes of all data, this could lead to the root username being changed, which is used in places such as the above snippet. What am I missing please?

**Comment by sroutier** [comment]
Hey Roy,

You are not missing anything. Infact you found a pretty embarrassing bug.... 
Just fixed it, thanks for submitting the issue. Totally did not see that one coming.

Cheers mate, Let me know if you have any other issues or questions.

/Seb.
