### ISSUE TITLE
Some problem when composer install

### ISSUE THREAD

**Issue by triabiy** [leskhq/Laravel-Enterprise-Starter-Kit#3]
Hi Sroutier,

I found some problem when running composer install :
Warnig : The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them. Your requirements could not be resolved to an installable set of packages.
 Problem 1
- Installation request for adldap2/adldap2 v5.0.8 -> satiffiable by adlap2/adldap2[v5.0.8]
- adldap2/adldap2 v5.0.8 requires ext-ldap \* -> the requested PHP extension ldap is missing from your system.
  Problem 2
- adldap2/adldap2 v5.0.8 requires ext-ldap \* -> the requested PHP extension ldap is missing from your system.
- sroutier/eloquent-ldap dev-master requires adlap2/adlap2 5.0.\* ->satisfiable by adldap2/adldap2[v5.0.8].
- Installation request for sroutier/eloquent-ldap dev-master -> satisfiable by sroutier/eloquent-ldap [dev-master].

**Comment by sroutier** [comment]
Hey there, 
Looks to me like you are missing the PHP extension LDAP. Part if the error states:
"...the requested PHP extension ldap is missing from your system."
Do you need a hand setting that up? What OS and version are you using? 
/s

**Comment by triabiy** [comment]
I use windows 7 ultimate 64bit

**Comment by sroutier** [comment]
Ok and how did you install PHP? With a package that came with Apache such as XAMPP, EasyPHP or WampServer? Or did you install it yourself and you are running it through IIS?

Side note: If you are familiar, even just a little, with Linux, I would totally recommend setting up Homestead for your PHP/Laravel development, it is really much easier than setting up Windows.
You can run homestead on Windows no problem.

**Comment by triabiy** [comment]
I use xampp & homestead on windows. before I ran composer install, I try to access l51esk.dev from browser and there appear Laravel 5.

**Comment by sroutier** [comment]
ok, so if you already have homestead running, just ssh into your homestead virtual host and run "composer install" in it. If your run "composer install" on Windows it most likely will complain about the missing PHP LDAP extension (unless you install it). 
If you want to see which PHP extensions are loaded create a PhpInfo page and hit it on a Web browser.
See http://www.cyberciti.biz/faq/how-do-i-test-php-installation-with-a-phpinfo-page/ for a quick guide.
/s

**Comment by dsnoeck** [comment]
Hi, I'm using homestead and I just got this error as well when running "composer install".
After a quick check, homestead doesn't provide ldap extension for PHP !
@sroutier, have you recently tested with homestead ? Am I missing something ?

**Comment by sroutier** [comment]
Hello @dsnoeck it's possible that homestead does not have the ldap extension for PHP installed. In that case you will have to installed it yourself.

A quick apt-get command should do it:

```
sudo apt-get install php5-ldap
```

Let me know if you have any problems.
/s

**Comment by dsnoeck** [comment]
Thanks for your quick reply.

So now homestead come with php7 so it was:
`sudo apt-get install php7.0-ldap`

**Comment by sroutier** [comment]
👍

**Comment by VickG** [comment]
what we intend on not using LDAP? can we someone not require that?

**Comment by sroutier** [comment]
If you do not intend on using the AD/LDAP authentication option you can simply set the configuration option `LDAP_ENABLED` to false in your `.env` file.

**Comment by jeanmfdias** [comment]
@dsnoeck thanks

**Comment by DazDotOne** [comment]
It's been a while since I installed PHP on my work machine which runs on Windows 10 so I can't really remember which additional extensions I installed, and coming from a linux background, I was p[retty much installing PHP on the fly. but I fixed this by simply un-commenting:

    ;extension=ldap

in `c:\PHP7\php.ini`

Funily enough though, no sooner than I fixed it for my native windows install, I created a simple(ish) dockerfile that makes it pretty easy to add ldap to PHP.

As a rough example (not tested in isolation):

````
FROM centos:centos7
... do some stuff...

# Install Apache
RUN yum -y install httpd mod_ldap

... do more stuff ...
RUN yum -y install php php-devel php-gd php-pdo php-soap \
php-xmlrpc php-xml php-ldap composer
````

**Comment by BigBigBoyVN** [comment]
> It's been a while since I installed PHP on my work machine which runs on Windows 10 so I can't really remember which additional extensions I installed, and coming from a linux background, I was p[retty much installing PHP on the fly. but I fixed this by simply un-commenting:
> 
> ```
> ;extension=ldap
> ```
> 
> in `c:\PHP7\php.ini`
> 
> Funily enough though, no sooner than I fixed it for my native windows install, I created a simple(ish) dockerfile that makes it pretty easy to add ldap to PHP.
> 
> As a rough example (not tested in isolation):
> 
> ```
> FROM centos:centos7
> ... do some stuff...
> 
> # Install Apache
> RUN yum -y install httpd mod_ldap
> 
> ... do more stuff ...
> RUN yum -y install php php-devel php-gd php-pdo php-soap \
> php-xmlrpc php-xml php-ldap composer
> ```

Thank you. Work for me.

**Comment by AnythingLinux** [comment]
use sudo apt-get install php-ldap for php 7.3.x
