### ISSUE TITLE
403 Forbidden instead of redirecting to login page

### ISSUE THREAD

**Issue by tamer-hassan** [leskhq/Laravel-Enterprise-Starter-Kit#30]
Per the doc, when enabled all guest or un-authenticated users will be redirected to the login page.
This is however not the case, and all pages result in 403 forbidden for guest users.

Edit: Actually getting 403 forbidden on all pages if I'm not logged in, regardless of whether walled garden is enabled.

**Comment by tamer-hassan** [comment]
Sorry, my mistake.. It seems .env was not updated properly (by me) during a merge, and so was still using WALLED_GARDEN instead of WALLED_GARDEN_ENABLED, per 5dbbdf8 .
With WALLED_GARDEN_ENABLED=true , all pages now redirect to login page as it should.

**Comment by sroutier** [comment]
Hey Tamer,

Sorry about the trouble. I changed the setting name to make it a little more clear.
Glad that you are still around.

Cheers.
/s
