### ISSUE TITLE
bootstrap modal does not reload the data

### ISSUE THREAD

**Issue by aquinotgr00** [leskhq/Laravel-Enterprise-Starter-Kit#31]
hello there,
why did the modal keep displaying the same content when i clicked the different button? In this example it's the delete button, when i click in the different column, the modal content is still displaying content from the last modal.
like this: i click the delete from user with ID 3->the modal displaying it's ID is 3->i closed the modal->i click user with ID 4->the modal still displaying it's ID is 3 instead of 4.
i tried to start over from your repository and i found a bunch update, but the problem is still the same.

ps: i'm really sorry for my poor english, and btw how do i get the update from your repository ? i already fork it and adding my own code

**Comment by sroutier** [comment]
Hello,

I will check your issue with the modal when I get back in front of my computer, I am on the road right now.
Check this article https://help.github.com/articles/syncing-a-fork/ to help you merging my changes into your repository.

Cheers.
/S

**Comment by sroutier** [comment]
Confirmed. Will fix asap.
Thanks.
/s

**Comment by sroutier** [comment]
One little href that should have been an src caused this rather important issue.
@shittyc0de thanks for checking it out and submitting an issue.
/s
