### ISSUE TITLE
after deleting a menu in admin-menu, the menu no longer loads

### ISSUE THREAD

**Issue by VickG** [leskhq/Laravel-Enterprise-Starter-Kit#32]
![unspecified](https://cloud.githubusercontent.com/assets/3667059/14691874/8d0b13e4-0708-11e6-92cc-bde71ae42d0e.png)
Hello,

Thanks for an awesome starter kit! I am using this in my next project. I like what you have done with the menus, but there seems to be a bug.

When I delete a menu, it prevents the menu from loading. In this case, I deleted the TEST ACL node, and the results can be viewed in my screenshot.

**Comment by sroutier** [comment]
Aye... That is not good. Let me see.

**Comment by sroutier** [comment]
Found the problem. It was created by allowing the deletion of menu nodes with children, this would break the referential integrity. Good find, thanks for submitting it.
/s
