### ISSUE TITLE
how to get users by group?

### ISSUE THREAD

**Issue by VickG** [leskhq/Laravel-Enterprise-Starter-Kit#33]
This gives me all users: 
$users = $this->user->pushCriteria(new UsersWithRoles())->pushCriteria(new UsersByUsernamesAscending())->paginate(100);

how do I get users from Role named "authors"?

thanks

**Comment by sroutier** [comment]
Hello,

If you want to use pure Eloquent try:

```
$authors = App\Models\Role::with('users')->where('name', 'authors')->first();
$users = $authors->users;
```

This will load the `authors` role and preload all it's associated users.

If you want to use the repository pattern, you will have to create your own criteria modeled after `App\Repositories\Criteria\Role\RolesWhereDisplayNameOrDescriptionLike`, use it to get the author role first, then its users.
Something like:

```
$authors = $this->role->pushCriteria(new RolesWhereNameIs('authors'))->first();
$users = $authors->users;
```

You probably also want to create a criteria to preload the users of a role modeled after `App\Repositories\Criteria\Role\RolesWithPermissions`.

Does that help?
/s

**Comment by sroutier** [comment]
Closing this, let me know if you have any other issues or questions.
Cheers.
/S
