### ISSUE TITLE
Session Changing

### ISSUE THREAD

**Issue by tobsbola** [leskhq/Laravel-Enterprise-Starter-Kit#34]
Hi all,

The app keeps loggin me out randomly on its own accord. Could you please suggest a way to go around this?

Thanks.

**Comment by tobsbola** [comment]
Also, its fine on say localhost/laravel/public, but logs out randomly on localhost:8080

**Comment by sroutier** [comment]
Hello @tobsbola,

Sorry for the late response. Unfortunately I have no idea. I have not run this project on an non-standard port much, but I spent all morning it on 8080 without any problems.

Are you still having this problem? Are you able to discern a pattern?
Can you describe your environment a little?

Cheers.
/S
