### ISSUE TITLE
how do I use the menubuilder for layout-top-nav layouts?

### ISSUE THREAD

**Issue by VickG** [leskhq/Laravel-Enterprise-Starter-Kit#37]
I have some views I want to have a top-navigation and not the side-bar navigation we see in ADMINLTE.

I have created views to follow the exact markup as we see here:
https://almsaeedstudio.com/themes/AdminLTE/pages/layout/top-nav.html

The only problem I am facing now is that I cannot "pull" in the menu using your menubuilder system to reflect the correct markup for layout-top-nav view.

The required markup style is:

```
<ul class="nav navbar-nav">
<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Link</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
</ul>
```

following code produces:
 {!! MenuBuilder::renderMenu('home', false)  !!}

```

<ul class="sidebar-menu">

    <li><a href="/dashboard"><i class="fa fa-dashboard"></i>&nbsp;<span>Dashboard</span></a>
    </li>
    <li><a href="/hf"><i class="fa fa-building"></i>&nbsp;<span>List of all HF</span></a>
    </li>
    <li><a href="/si"><i class="fa fa-sun-o"></i>&nbsp;<span>List of all SI</span></a>
    </li>
    <li class="treeview"><a href="/test-acl/home"><i class="fa fa-bolt"></i><span>Test ACL</span><i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
            <li><a href="/test-acl/admins"><i class="fa fa-file"></i>&nbsp;<span>Admins</span></a>
            </li>
            <li><a href="/test-acl/basic-authenticated"><i class="fa fa-file"></i>&nbsp;<span>Basic authenticated</span></a>
            </li>
            <li><a href="/test-acl/guest-only"><i class="fa fa-file"></i>&nbsp;<span>Guest Only</span></a>
            </li>
            <li><a href="/test-acl/open-to-all"><i class="fa fa-file"></i>&nbsp;<span>Open to all</span></a>
            </li>
        </ul>
    </li>

</ul>


```

Any quick solutions to this? I like that it's keeping the icons...but the markup layout is not correct in my case.

**Comment by sroutier** [comment]
Hello @VickG,

Have you tried using a different menu handler? 

By default the project is configured to use the `L51ESKSecuredMenuHandler.php`, that is why the call to `{!! MenuBuilder::renderMenu('home', false) !!}` renders a `sidebar-menu`. 

But you can either:
1. Change the system wide configuration in your `.env` by specifying the `MENU_BUILDER_FRAMEWORK_HANDLER` variable as shown in the `.env.example`.
2. Specify a different menu handler when you call the `MenuBuilder::renderMenu(...)`. This is probably the best option if you want to use both sidebar and topbar within one project. Look at the file `/resources/themes/default/views/test_menus.blade.php` for an example, there you will see a call to `{!! MenuBuilder::renderMenu('admin', false, '\App\Handlers\BootstrapLightMenuHandler')  !!}` that renders a topbar style menu.
3. If none of the included menu handlers satisfy your requirements, you could always write your own. Simply create a new class under `\App\Handlers\` and follow the existing classes as examples. Don't forget to either configure it as the default handler (option 1) or specify it when calling the `renderMenu()` method (Option 2).

Does that answer your question?
Let me know how if you have any other questions?

Cheers.
/S

**Comment by VickG** [comment]
Thank you! It does! Please close this

**Comment by sroutier** [comment]
Glad to hear it. 
Let me know if you have any other questions. 
/s
