### ISSUE TITLE
Call to a member function getGroups() / getName() on a non-object

### ISSUE THREAD

**Issue by tamer-hassan** [leskhq/Laravel-Enterprise-Starter-Kit#38]
As the title says, when logging in with a particular LDAP (MS AD) account, I get the following error:

`FatalErrorException in HasMemberOfTrait.php line 73:
Call to a member function getGroups() on a non-object`

I changed the `.env` file:
`LDAP_RECURSIVE_GROUPS=false`

Then, when logging in again with that same ldap account, I get the following:
`FatalErrorException in EloquentLDAPUserProvider.php line 536:
Call to a memeber function getName() on a non-object`

How to troubleshoot?

**Comment by sroutier** [comment]
Strange... You can query the MS AD using the [dsquery user](https://technet.microsoft.com/en-us/library/cc725702%28v=ws.11%29.aspx) command from [dsquery](https://technet.microsoft.com/en-us/library/cc732952%28v=ws.11%29.aspx?f=255&MSPPError=-2147217396), it will give you a print out of the user's properties and you can try to compare them against another user that works to see if you can find a difference. But all the command line options can be tricky to get right.

You could also install the [AD Inspector](https://github.com/sroutier/L51ESK-Module_ActiveDirectoryInspector) module in your installation of L51ESK to probe your MS AD configuration. Again try and compare two users to locate a difference.

Good luck, let me know how this works for you.
/s
