### ISSUE TITLE
LDAP_GROUP_MODEL confusion

### ISSUE THREAD

**Issue by tamer-hassan** [leskhq/Laravel-Enterprise-Starter-Kit#4]
Upon installation (and after all configuration), I am greeted with the following after trying to login with an AD account:
FatalErrorException in EloquentLDAPUserProvider.php line 219: Class '\App\Models\Group' not found

The comment from eloquent-ldap/config/config.php states:
    | Name of model that represents a group or role. This is the model that
    | will automatically be granted membership to based on the user's LDAP
    | membership if the option 'assign_group' is enabled.

however, I cannot find an option named "assign_group" enabled.

Reading the documentation of eloquent-ldap, it clearly states:
For a concrete example of this package used in an active project, see sroutier/laravel-5.1-enterprise-starter-kit. Note that in that project this package is used in combination with Zizaco/entrust to provide role based authorization, **therefore there is no group model, but instead a role model.**

I am completely confused.

**Comment by tamer-hassan** [comment]
Maybe I overthought this. Simply changing to:
`LDAP_GROUP_MODEL=App\Models\Role` instead of App\Models\Group
Solves the issue.

**Comment by sroutier** [comment]
Hey there, sorry about the complete confusion. Looks like the example ".env" file that I packaged was broken. Good news is that you found the fix, easy enough as it turns out but I will fix the example config file ASAP. Thanks for pointing it out.
/Seb
