### ISSUE TITLE
when running composer update, I am getting an error

### ISSUE THREAD

**Issue by VickG** [leskhq/Laravel-Enterprise-Starter-Kit#43]
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)  
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package yaap/theme dev-laravel-5.1 exists as yaap/theme[1.0.0, 1.0.x-dev, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 2.0, 2.1, 2.2.0, dev-develop, dev-master, v2.1.1] but these are rejected by your constraint.

Any ideas?

**Comment by sroutier** [comment]
Looks like the "version" that I initially set as a dependency in composer.json is no longer available.
Try changing the line:

```
"yaap/theme": "dev-laravel-5.1",
```

With this

```
"yaap/theme": "2.*",
```

I have not tried that version yet, so you will have to tell me if you find any compatibility issues.
If it all works for me send me a quick PR and i will merge it.

Good luck.
/S

**Comment by sroutier** [comment]
I just updated the version requirements for the package 'yaap\theme'.
Looks to be working fine for me.
Try it please.
/s
