### ISSUE TITLE
Menu Rendering Not Showing New Modules

### ISSUE THREAD

**Issue by sammy-kariuki** [leskhq/Laravel-Enterprise-Starter-Kit#45]
Hi, 
The new issue I have discovered is the fact that at the moment, the module package is not creating menu entries when a module is initiated. I have attached a screenshot so that you can see. The 'Members' Module is enabled and initialized. But it is not added on the Menu.

Please advice me if there is something I'm doing wrong and what I should change.

Thank you.

**Comment by sammy-kariuki** [comment]
Solution:
I just found out that I was skipping some preliminary steps when it comes to creating modules such as editing the manifest files. Then I was enabling a module before I initialize it. This caused the menu entries to be made after the menu was already enabled and so couldn't show immediately on the menu. 

Thank you :)

**Comment by sroutier** [comment]
Glad you resolved the issue. I will see if I can add a few notes in the README to make this easier to understand.

Cheers.
/Seb.
