### ISSUE TITLE
Proposal for Laravel-5.2.*-enterprise-starter-kit migration.

### ISSUE THREAD

**Issue by vrkansagara** [leskhq/Laravel-Enterprise-Starter-Kit#47]

**Comment by sroutier** [comment]
Hello,

I do not have any plans to get this project working on Laravel 5.2 at the moment. In my opinion, the support model for non-LTS release is too short to justify investing the time to get the Enterprise Starter Kit working properly with Laravel 5.2. For all I know it may work just fine, I have not tested it.
When developing for an enterprise and a complex production environment, having a well established support policy that will last a few years is very important. Laravel 5.1 being an LTS release that will get security updates for 3 years make it the perfect release to work with even if it will not have all the bells and whistles of the latest release.
I suspect that ESK will continue to target Laravel 5.1 until the next LTS version is released.

That being said, if you want to try the ESK with a newer version of Laravel, please let me know how it works out for you. 
Also if you want to submit a PR to allows support for more recent version of Laravel, I would gladly incorporate it, either in the main stream if the changes do not introduce any incompatibilities, or in a new and separate stream.

Thank you for looking at the project and your proposal.
Let me know if you have any other questions or ideas.

/s
