### ISSUE TITLE
adding email verification after registration

### ISSUE THREAD

**Issue by mohd-aidi** [leskhq/Laravel-Enterprise-Starter-Kit#49]
Hi,

i added new email authentication for registration. means after user registered, he need to click a url with token in his email to enable the account. 

But the problem is system keep kicking the url to login page. i use AuthController.

**Comment by mohd-aidi** [comment]
i believe this is because of the url is having {token} in url. 

i put the path 'auth/activation' in walled-garden but its not working. but when i put the whole path with token it works. eg 'auth/activation/ddcaea3df51036f189a85c58119c0ffef3744fc9dffaf8c470e803454f9df8d6'

how to dynamically exempt this path without the token?

**Comment by mohd-aidi** [comment]
I solved it using exemptions-regex in walled-garden. i put the path in regex so the function will preg_match this path and return true.

'exemptions-regex' => [
        '/password\/reset\/.*/',
        '/auth\/activation/',
    ],

**Comment by sroutier** [comment]
Hey there,

Good find, adding your entry to the exemptions-regex list was the right way
to get around the Walled Garden check.
Question for you: How did you implement the email/account validation? Did
you use a pre-existing module or did you write that functionality yourself?

I would like to incorporate this into the project if you do not mind
sending me a PR, I can have a look at it.

Thanks.
/S

**Comment by mohd-aidi** [comment]
i wrote the code based on tutorial below..its not a plugin..but you need to modify some code here and there for it to function.

https://blog.damirmiladinov.com/laravel/laravel-5.2-email-verification-with-activation-code.html#.V8eNlfl94dX
