### ISSUE TITLE
Upgrade to Laravel 5.3

### ISSUE THREAD

**Issue by moebaca** [leskhq/Laravel-Enterprise-Starter-Kit#50]
Hi, 

I'm a new developer using this project and have nothing but good things to say about it. However, there are some new features in Laravel 5.3 that I would like to take advantage of (quick sortable columns, channels, etc.) that aren't in 5.1. Could you give me an idea of how feasible an upgrade would be for this existing project?

Thanks!

**Comment by sroutier** [comment]
Hey Matthew,

I have not looked in details at 5.3 yet so I will not be able to give you much guidance on the specifics. One problem with upgrading a project of this size is that a lot of feature is bundled together from packages, and these packages may not be 5.3 compatible just yet. It may be hard, specially for a new developer to figure out which part breaks and why, and you may have to wait for the other developer to upgrade his package. Of course you could always fix them yourself and contribute to the project.

I would almost recommend that you start from the beginning with a empty Laravel project and add one functionality at the time. Trying to reuse pre-existing packages as much as possible. That is what I did for this project, and this is probably the approach that I will follow once the next LTS version is released.

Laravel implementation is very clean and well documented, so it will be a great place to learn. I hope that you enjoy it as much as I have. Let me know if you have any questions and I will try to answer them as best I can.

Cheers.
/S

**Comment by moebaca** [comment]
Ah, thank you for the very rapid response. I figured it wouldn't be a trivial process by any stretch but wanted to check with you to verify.

Thanks again for putting together this excellent package! I hope I can contribute in the future as I progress my skills in web application development!
