### ISSUE TITLE
Remove old loaded routes on loading.

### ISSUE THREAD

**Issue by Clivern** [leskhq/Laravel-Enterprise-Starter-Kit#51]
Is there is any way i can remove old loaded routes from the database when i try to load a new routes. I know it should be performed on method `loadLaravelRoutes` in `\App\Models\Route` class.

**Comment by sroutier** [comment]
Hey @Clivern, you are right currently there is not automatic way to have old loaded routes deleted from the database. I simply never thought about that, good catch. 
I do not think that there is any use case for wanting to keep any old route that would have been removed from the source `app/Http/routes.php`, so I think simply removing them during the load call would make sense, of course then the load call will have to be renamed to sync or something like that.
Any thoughts or objection on this approach?

/s

**Comment by Clivern** [comment]
Hi @sroutier, this approach is perfect :+1:

**Comment by sroutier** [comment]
Done. Give it a try & let me know.
/S

**Comment by Clivern** [comment]
Ok :+1:

**Comment by sroutier** [comment]
Cool. Enjoy!
