### ISSUE TITLE
Update  list of settings with existing .env file.

### ISSUE THREAD

**Issue by vrkansagara** [leskhq/Laravel-Enterprise-Starter-Kit#54]
Do we update the " List of settings" functionality under the admin>setting into dashboard with existing .env file so both the details are update.

Also show the sensitive variable name as per .env into dashboard.

Also add `.env-*`  environment support.

**Comment by sroutier** [comment]
Hello @vrkansagara, 

Hopefully I understood your question and request properly, if I did not please do not hesitate to ask again.

1) You are correct initially the settings must be manually loaded from the "Admin > Settings" page by clicking on the "Load" button. Once the settings loaded, the content of the `.env` file is ignored in favour of the settings for all values that where not filtered out.

2) Which sensitive variable name did you want to show? During the loading process some sensitive variable will not be loaded from the `.env` file into the settings. Such variables are core Laravel variables and it seemed safer to prevent a running system from editing it's own value on-the-fly. That is why they were filtered out from the loading process.

3) Do you mean to add `.env-*` file to the files used as source to load settings? I am not sure I understand why you would want that or what it is that you are asking. Can you clarify a little please.

Thank you.
/s

**Comment by vrkansagara** [comment]
Hello @sroutier 

> 1) You are correct initially the settings must be manually loaded from the "Admin > Settings" page by clicking on the "Load" button. Once the settings loaded, the content of the .env file is ignored in favour of the settings for all values that where not filtered out.

While initiation of the settings I want to see the case sensitive `Name` and it's `Value` exactly  the same as whet it appear into `.env` file so it will give me a clear vision that I am sync the `.env` file not just updating the database value.   

> 2) Which sensitive variable name did you want to show? During the loading process some sensitive variable will not be loaded from the .env file into the settings. Such variables are core Laravel variables and it seemed safer to prevent a running system from editing it's own value on-the-fly. That is why they were filtered out from the loading process.

Yes, You are right on this and I am agree with you :+1:  that default variable provided by the laravel `.env` file must be filtered out for the security reason. Because I have seen that in development process people using his/her personal detail which is exposed into application and it is not a best practice.

> 3) Do you mean to add .env-\* file to the files used as source to load settings? I am not sure I understand why you would want that or what it is that you are asking. Can you clarify a little please.

Here I want to propose that in dashboard I can able to see default value what is set into different `.env-dev` and `.env-pro` file so it will easily comparable in admin>settings path with easily view-able  like name and value field followed by default value of  `.env` as default(current) , `.env-dev` as (Development), `.env-prod` as (Production).

Here I will add one more feature to this. Let say some how the `.env` file will removed by anybody using terminal in that case application would be crashed. The possible solution we add some kind of functionality the will generate a `.env` from given environment and place/replace to existing one. 

The benefit of this feature is easily recoverable of `.env` file based on selected environment only.

Also need to enclose the value with `'` single quote or `"` double quote.

**Comment by sroutier** [comment]
Hello @vrkansagara,

I just implemented a few things about the Settings that you may want to look into.

Following your suggestion, I changed all settings and config options used by LESK to have a matching case, while leaving the core Laravel config option untouched.

I also implemented a way to optionally encrypt the value of a setting and to have it automatically decrypted on demand.

Finally, there is 4 new Artisan commands to set, get, forget and retrieve all settings. This should allow you to recover the settings as your requested.

Hope that helps. Let me know what you think.

Cheers.
/S

**Comment by vrkansagara** [comment]
it's good to here you on this with changes. Thanks @sroutier  I will look into and update you with the same. Again thanks.

And please if you applying a patch then please  use `#` with PR number so I can  quickly look into. Thanks.
