### ISSUE TITLE
Suggestions on some modifications and additions to the L51ESK

### ISSUE THREAD

**Issue by salhdev** [leskhq/Laravel-Enterprise-Starter-Kit#56]
Good morning, 

**1. Move all test and demo code to a module** :
As I was testing around with modules, I thought it would be good to move all the test and demo stuff under a module which would bring the following benefits : 
- Test the module functionalities as well as the actual L51ESK functionalities
- Put all the unnecessary code into one place that can be disabled or removed
- Always have a clean project start point 

**2. Add the Module Composer Support :** 
Check [the cafeinated doc](https://github.com/caffeinated/modules/wiki/Composer) this will introduce two important functions: 
- Module dependency requirements on our new modules => you can split big functionality in smaller independent modules while requiring that the other be installed to run the whole thing.
- Package dependency required by the module itself and not by the rest, so the composer.json doesn't get cluttered by all those packages that belong to a module.

**3. Define guidelines for Module table names :** 

Regards,
S.

**Comment by sroutier** [comment]
All great ideas thanks.
/s

**Comment by sroutier** [comment]
Hello @sraffali,

Can you elaborate a little about what you have in mind for your 3rd suggestion?
What type of guidelines would you see as being helpful while at the same time not limiting the module. Perhaps if you have a use case or two.

Thanks.
/s

**Comment by salhdev** [comment]
Hi @sroutier, 
I was thinking like table name should be like 'module_slug_table_name' or some sort of uniqueness to keep database clean and readable and of course to avoid duplicate table names across modules.
Cheers,
S.

**Comment by sroutier** [comment]
Hello @sraffali,

I implemented the improvements (1 & 3) that you suggested. Improvement 2 is a little more involved, and in fact I should try to upgrade the lesk-module package to catch up with the original source, so I will open an other issue to track this work separately.

Thanks a lot for these suggestions.
Cheers.
/S
