### ISSUE TITLE
New Project in Windows 10 using wamp gives an email issue on user creation

### ISSUE THREAD

**Issue by sammy-kariuki** [leskhq/Laravel-Enterprise-Starter-Kit#57]
Hello, 
Just cloned and followed the instructions given in the readme. Managed to log in successfully. However, when trying to create a new user, I get this error:

mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()

I am using wamp with php 5.6. I have tried everything but I don't understand what the problem could be. Why is it trying to send an email? I have set disabled lern by having it set as follows:

LERN.ENABLED=false

Any help?

**Comment by sroutier** [comment]
Hello @SammyHash,

Can you check the log files (laravel & http)? You may be able to find a stack trace in there that can help us narrow down the source of the problem.

I I were to guess, I would ask you to check to see if the the other settings that can trigger an email:

```
...
APP.EMAIL_NOTIFICATIONS_ENABLED=false
...
AUTH.EMAIL_VALIDATION=true
...
```

Let me know how it goes and we will take it from there.
/s

**Comment by sammy-kariuki** [comment]
Hi,
Thank you for the fast reply. The settings you have indicated have been set to false as shown below:

APP.EMAIL_NOTIFICATIONS_ENABLED=false
AUTH.EMAIL_VALIDATION=false

On the laravel log, I am getting something like this:

> #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'mail(): Failed ...', 'C:\wamp\www\del...', 135, Array)
> #1 C:\wamp\www\project\vendor\monolog\monolog\src\Monolog\Handler\NativeMailerHandler.php(135): mail('lesk.admin@emai...', '[LESK]: An Exce...', '[2016-09-20 14:...', 'From: myemail...', '')
> #2 C:\wamp\www\project\vendor\monolog\monolog\src\Monolog\Handler\MailHandler.php(53): Monolog\Handler\NativeMailerHandler->send('[2016-09-20 14:...', Array)
> #3 C:\wamp\www\project\bootstrap\cache\compiled.php(13336): Monolog\Handler\MailHandler->write(Array)
> #4 C:\wamp\www\project\bootstrap\cache\compiled.php(13097): Monolog\Handler\AbstractProcessingHandler->handle(Array)
> #5 C:\wamp\www\project\bootstrap\cache\compiled.php(13203): Monolog\Logger->addRecord(500, ' ...', Array)
> #6 C:\wamp\www\project\vendor\tylercd100\laravel-notify\src\Drivers\Base.php(122): Monolog\Logger->critical('<div>\r\n     ...', Array)
> #7 C:\wamp\www\project\vendor\tylercd100\lern\src\Components\Notifier.php(161): Tylercd100\Notify\Drivers\Base->critical('<div>\r\n     ...', Array)
> #8 C:\wamp\www\project\vendor\tylercd100\lern\src\LERN.php(78): Tylercd100\LERN\Components\Notifier->send(Object(ErrorException))
> #9 C:\wamp\www\project\vendor\tylercd100\lern\src\LERN.php(55): Tylercd100\LERN\LERN->notify(Object(ErrorException))
> #10 C:\wamp\www\project\app\Exceptions\Handler.php(52): Tylercd100\LERN\LERN->handle(Object(ErrorException))
> #11 C:\wamp\www\project\bootstrap\cache\compiled.php(2323): App\Exceptions\Handler->report(Object(ErrorException))
> #12 C:\wamp\www\project\bootstrap\cache\compiled.php(2242): Illuminate\Foundation\Http\Kernel->reportException(Object(ErrorException))
> #13 C:\wamp\www\project\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
> #14 {main}
> 
> Next exception 'Tylercd100\LERN\Exceptions\NotifierFailedException' with message 'mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set()' in C:\wamp\www\project\vendor\tylercd100\lern\src\Components\Notifier.php:166
> Stack trace:
> #0 C:\wamp\www\project\vendor\tylercd100\lern\src\LERN.php(78): Tylercd100\LERN\Components\Notifier->send(Object(ErrorException))
> #1 C:\wamp\www\project\vendor\tylercd100\lern\src\LERN.php(55): Tylercd100\LERN\LERN->notify(Object(ErrorException))
> #2 C:\wamp\www\project\app\Exceptions\Handler.php(52): Tylercd100\LERN\LERN->handle(Object(ErrorException))
> #3 C:\wamp\www\project\bootstrap\cache\compiled.php(2323): App\Exceptions\Handler->report(Object(ErrorException))
> #4 C:\wamp\www\project\bootstrap\cache\compiled.php(2242): Illuminate\Foundation\Http\Kernel->reportException(Object(ErrorException))
> #5 C:\wamp\www\project\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
> #6 {main}

**Comment by sammy-kariuki** [comment]
I have just installed the same project in linux's homestead. When I try to visit Admin>Security>Users and then click on "Create new user", I get the following error:

`Undefined variable: themes (View: /home/vagrant/sites/project/resources/themes/default/partials/_user_form.blade.php) (View: /home/vagrant/sites/project/resources/themes/default/partials/_user_form.blade.php)`

I think the issue  is that the email function is triggered when there is an error. 

Sam.

**Comment by sroutier** [comment]
Hello @SammyHash,

I changed a little how the LERN package was being invoked depending on a couple of new configuration items named:

```
LERN.ENABLE_RECORD=true
LERN.ENABLE_NOTIFY=true
```

Please pull an update of the code and edit your `.env` file. Hopefully you will not have this problem anymore.

Let me know how it goes. 
Now I will move on the fix the "Create User" function!

Thanks for try all this and submitting issue. Sorry it's been so hard for you but with all our combined effort it will get better. I appreciate the assistance.

/S

**Comment by sammy-kariuki** [comment]
Thank you for the response. I will pull the code and test; then reply here. 

You are welcome.

**Comment by sroutier** [comment]
FYI: I also just submitted a fix for the error that you were seeing when trying to create a new user.
Cheers.
/S

**Comment by sammy-kariuki** [comment]
Hi, 
I have tested on windows and the errors are now done. I can also be able to create a user. 

One bug though;
When I create a user, then log into that user and try updating their profile, they automatically lose the roles I had designated to them. For example, I have a module 'Customers', if I assign the role 'customer-module-users' to the user 'johny test' together with the permission 'use-customer-module-functions', he will automatically lose that role and permission when he tries to update his profile. 

Could the bug be on my manifest?

I have tried changing several things but nothing seems to solve it. I have also made sure that my roles have been set up correctly. 

Please let me know. 

Thanks.

**Comment by sroutier** [comment]
Hello Sammy,

Glad the user creation bug was resolved.

Regarding the disappearing role, I just tested creating a user with specific role and permission assigned and upon first login the role and permission where retained.

I am thinking that perhaps you are experiencing a feature of the application.
Are these user originating from Microsoft Active Directory?
Do you have the settings `LDAP.REPLICATE_GROUP_MEMBERSHIP` and `LDAP.RESYNC_ON_LOGIN` enabled?
Does your role `customer-module-users` have the option `Re-sync on login` enabled?

When users are authenticated from MSAD and these options enabled, the application will reset role membership and attempt to match and grant existing roles with groups from MSAD that the user is a member of. 

Let me know.
/S

**Comment by sammy-kariuki** [comment]
Hi, 
I am not using LADP. I have disabled all of them because I don't need them in the project. My settings are as follows:

> LDAP.ENABLED=false
> LDAP.DEBUG=false
> LDAP.SERVER_TYPE=MSAD
> LDAP.CREATE_ACCOUNTS=false
> LDAP.REPLICATE_GROUP_MEMBERSHIP=false
> LDAP.RESYNC_ON_LOGIN=false
> LDAP.GROUP_MODEL=App\Models\Role
> LDAP.LABEL_INTERNAL=internal
> LDAP.LABEL_LDAP=ldap
> LDAP.ACCOUNT_SUFFIX=@company.com
> LDAP.BASE_DN=DC=department,DC=company,DC=com
> LDAP.SERVER=ldapsrv01.company.com
> LDAP.PORT=389
> LDAP.USER_NAME=ldap_reader
> LDAP.PASSWORD=PaSsWoRd
> LDAP.RETURN_REAL_PRIMARY_GROUP=true
> LDAP.SECURED=false
> LDAP.SECURED_PORT=636
> LDAP.RECURSIVE_GROUPS=false
> LDAP.SSO=false
> LDAP.USERNAME_FIELD=samaccountname
> LDAP.EMAIL_FIELD=userprincipalname
> LDAP.FIRST_NAME_FIELD=givenname
> LDAP.LAST_NAME_FIELD=sn
> LDAP.USER_FILTER=(&(objectcategory=person)(samaccountname=%username))

As you can see most things are disabled there. When the user logs in, they are able to see the roles given, however, if they try to update their profile or change their password, the roles disappear.

I know there is a possibility that I might be doing something wrong, please bear with me. 

Thank you.

**Comment by sroutier** [comment]
Not good @SammyHash, using the latest info you provided I was able to reproduce the problem.
I will look into fixing this asap.
/s

**Comment by sroutier** [comment]
OK @SammyHash,

Just submitted a fix. This should do it. Let me know.

/s
