### ISSUE TITLE
Warning: Rename project.

### ISSUE THREAD

**Issue by sroutier** [leskhq/Laravel-Enterprise-Starter-Kit#58]
Hello,

Trying to give a fair warning to all people listening: I intend to rename the project and change the repository URL to match. I will probably change to name early next week.

The name will be changed from "laravel-5.1-enterprise-starter-kit" to "laravel-enterprise-starter-kit". Essentially dropping the 5.1 version label from the project name.

I hope that this will not inconvenience too many people, but I think that this minor name change is an important step toward the growth and maintenance ahead.

If you forked your own copy of the project, you should not have anything to do as GitHub will update the reference to the originating project automatically, you will be able to continue working with your own repository just as before.
If you are getting your updates directly from this repository, all that should be required to do on your end is to update the git remote URL. 
To prevent people from getting lost, I will create a new and separate project with the old name that will only contain a README file with instructions on to update your git configuration and a pointer to the original project at it's new location.

As usual, please let me know if you have any question, concerns or comments.

Cheers.
/S

**Comment by sammy-kariuki** [comment]
Noted. 

Cheers.

**Comment by sroutier** [comment]
I renamed the project last week and haven't had any problems, nor as anybody reported any.
Closing this issue for now.
/S
