### ISSUE TITLE
Let users change their password

### ISSUE THREAD

**Issue by dsnoeck** [leskhq/Laravel-Enterprise-Starter-Kit#59]
Hi,

This starter-kit is awesome, thanks.

I have created several users, but I don't find how they can change them self their password.
Is there any screen for that ? Or should I have to create it myself ?

**Comment by sroutier** [comment]
Allo Damien,

Glad you find the project useful.

Each user should be able to change their own password from their profile page accessible when they click on their icon/name on the top right using the default theme. 

This is a change that was introduced a few months ago, perhaps you do not have an updated repository.

Give it a try and let me know if you have any issues.

Salut.
/s

**Comment by dsnoeck** [comment]
Whaou, that was quick to answer.
Right, my version is from May. I will pull your latest changes.
Many thanks.

Bonne fin de journée ;-)

**Comment by sroutier** [comment]
Damien,

I'll assume that you have updated your repository and found the how a user can change his own password. I will close this issue for now but if you still have any problem with this please re-open it.

Cheers.
/s

**Comment by dsnoeck** [comment]
@sroutier, I have updated my repo (many thanks for the new registration process). When I click on the logo, I can then see the profile button, but when a regular authenticated user try to access it, he get "Error 403". I didn't have find any role or permission to give him the access to access only his profile. FYI, he can access the dashboard which is part of the same route group.

**Comment by sroutier** [comment]
Hello Damien,

Are you sure? I just tested it with a clean git clone and an authenticated regular user (not root) is able to click on the profile button and access it. I was also able to change the password, set some settings, log out and logged back in.

Could it be that you updated the code (git pull) but did not update the database or the routes in the dynamic routing table used as part of the security process to authenticate access to pages/route? That is usually where I make a mistake.

Admittedly, LESK does not have a clean and satisfactory way to upgrade from a previous version, yet. I am also not keeping any sort of changelog file to help you guys upgrade... I haven't figured out all the details of how I want to handle all this yet. Once I cut the first 1.0 version I will be much more careful, but things are still very much in development at the moment and I am open to suggestions if you have any.

So to fix your problem, you may only need to load the new routes from the "admin > security > routes" by clicking on the button, but if your copy of LESK was from May I would recommend that you try it with a clean project and new DB, lots of things have changed. Let me know.

Cheers.
/s

**Comment by dsnoeck** [comment]
Ok, thanks for the details. I will look at it and let you know.

**Comment by sroutier** [comment]
Closing this for now @dsnoeck. If you still have any issues with this or anything else do not hesitate to contact me.
Cheers.
/s
