### ISSUE TITLE
npm install errors with ENOENT 34

### ISSUE THREAD

**Issue by tamer-hassan** [leskhq/Laravel-Enterprise-Starter-Kit#6]
I ran into this issue twice
first time I thought I solved it with:
`touch .npmignore` in the project root then rerunning `npm install`
per the solution here: http://stackoverflow.com/questions/17990647/npm-install-errors-with-error-enoent-chmod
then I encountered another error (both on Ubuntu Server 14.04 and Linux Mint 17.1 Desktop) where it was looking for a "node" binary instead of a "nodejs" binary.
For that I had to:
sudo ln -s /usr/bin/nodejs /usr/bin/node

Perhaps these two steps should be noted in the documentation, to save others the time and research effort in solving this.

**Comment by sroutier** [comment]
Thanks for the tips, I noted both in the README.
/s
