### ISSUE TITLE
Menu not displayed in dashboard

### ISSUE THREAD

**Issue by orijmm** [leskhq/Laravel-Enterprise-Starter-Kit#61]
when I create a new menu appears in the treeview but not in the menus of the dashboard

**Comment by sroutier** [comment]
Hello @orijmm,

2 factors will affect the visibility of a menu item:
1) Is it enabled?
2) Does the user have permission to see it. Permission are inherited from routes or if no route is assigned it can be specified for the menu item.

Additionally, a menu container will not be visible if none of it's children are visible.

Glad that you are giving the project a try. Hopefully this answer helps you but let me know if it does not.

Cheers.
/S

**Comment by orijmm** [comment]
1) yes it enabled

2) I add a permission to the menu and it work.

Thanks :)

**Comment by sroutier** [comment]
Glad that you were able to find the source of the problem. Let me know if you have any other problems or questions.
/s
