### ISSUE TITLE
API

### ISSUE THREAD

**Issue by mohd-aidi** [leskhq/Laravel-Enterprise-Starter-Kit#68]
Hi, 

do you have any thought about integrate with API?any advice on how i can implement this API in lesk?

thank you very much in advance.

**Comment by sroutier** [comment]
Hello @mohd-aidi,

Is there a particular API that you had in mind to integrate with?

/s

**Comment by mohd-aidi** [comment]
yes, i'm thinking to integrate with REST API. 
I always have problem when it comes to handle for authentication and token.

**Comment by sroutier** [comment]
Sorry @mohd-aidi, I am still not clear what you are trying to do. Try to explain it with more details and I may be able to assist you.
/s
