### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by wujusz** [leskhq/Laravel-Enterprise-Starter-Kit#7]
hi,

When install all components i have blank page. 
All urls:
local.com/users 
local.com/roles
etc returns 404. What is wrong?

I am using mint linux 17.2 and apache 2.4.7

**Comment by isaqueprofeta** [comment]
Have you done changing permissions to web server write on storage/framework and storage/logs? Have a look at http://laravel.com/docs/5.1#installation

**Comment by sroutier** [comment]
Hello @wujusz, have you been able to resolve your issue? Can I close this issue?
I am adding some details to the README to avoid this issue and a few others in the future.
Thanks @isaqueprofeta for the assist.

/s

**Comment by sroutier** [comment]
Documentation updated with note to set permission on 'storage' folders.
