### ISSUE TITLE
LESK: Provide method to make small logo text sizeable.

### ISSUE THREAD

**Issue by sroutier** [leskhq/Laravel-Enterprise-Starter-Kit#72]
The small logo on the top left area that defaults to LESK when a user collapses the left bar defaults to a rather large font. It would be nice if the font size could be configurable.

**Comment by richa-coder** [comment]
Can i help it?

**Comment by sroutier** [comment]
Hello @richa-coder,

By all means, if you have any ideas and want to contribute, submit a pull request.
I think there is already one for this particular issue, but I haven't reviewed it yet. Did you have something else in mind?

Cheers.
/s
