### ISSUE TITLE
Module menus.

### ISSUE THREAD

**Issue by waleyson** [leskhq/Laravel-Enterprise-Starter-Kit#78]

**Comment by sroutier** [comment]
Hello @waleyson,

Glad that you find LESK useful and welcome to the Laravel community.

Please try to use the description field when creating an issue or asking a question, having super long titles makes it hard for the reader to understand the issue.

The way modules function is ultimately up the the module developer, but if they are following the guidelines, in order for a module menu to show-up they must not only be initialized but also enabled. Then if you want to have the menu(s) of a module appear under the main home menu, all you have to do is move each menu under a different parent. 
You can do this using one of two ways, the manual way or the programmatic way.
1) The manual way involves using the menu manager page located under (/admin/menus).
2) To use the programmatic way you have to locate the home menu, locate the module menu, and assign the home parent to the module menu.

I hope that this points you in the right direction. Let me know if you have any other questions.
Thanks.
/S

**Comment by waleyson** [comment]
thanks alot that actually resolved the issue.

**Comment by sroutier** [comment]
:+1:
