### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by esuveyke** [leskhq/Laravel-Enterprise-Starter-Kit#8]
Im noticing a bunch of Integrity constraint violations - this one occurs when you try to create a role.  Note user_id is missing.

---

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`enterprise`.`role_user`, CONSTRAINT `role_user_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) (SQL: insert into `role_user` (`role_id`, `user_id`) values (9, ))

---

**Comment by sroutier** [comment]
Thanks for the report, I will look at it soon. Someone stole my laptop on Tuesday, so aside from being a little ticked-off, I am struggling right now... Apple's Time Machine backup is a fantastic well implemented solution. I did not loose a thing from my working folders, 40 minutes from un-boxing and I was back to an exact replica of my laptop! But all my VMware machine have to be rebuilt, my backup was old and I had excluded them from Time Machine as they were too big. Lesson learned... 

What DB are you using? MySQL or something else?

Thanks.
/s

**Comment by danswiser** [comment]
I'm having the same problem using mariadb/mysql. When I create a user, I'm not getting any roles to choose from. When I try to create a role, with Basic authenticated selected, I get the same errors I get when creating a user.

**1/2**
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`laravel`.`role_user`, CONSTRAINT `role_user_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)

**2/2**
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`laravel`.`role_user`, CONSTRAINT `role_user_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) (SQL: insert into `role_user` (`role_id`, `user_id`) values (8, ))

**Comment by sroutier** [comment]
Found a few issues due to my use of SQLite3 as the default database for quick development. I will be more diligent in testing things with MySQL from now on. Sorry about that.
