### ISSUE TITLE
how to upgrade to laravel 5.3 :)

### ISSUE THREAD

**Issue by sugengsuprayogi** [leskhq/Laravel-Enterprise-Starter-Kit#81]
how to upgrade to laravel 5.3 :)

**Comment by sroutier** [comment]
Hello @sugengsuprayogi,

Sorry Laravel 5.3 is not currently officially supported. I am concentrating on the LTS releases as stability is more important for enterprise deployment. Laravel 5.5 is planned to be the next LTS release.
That is not to say that upgrading to 5.3 is not possible, and in fact if you where to provided a PR for it, I would consider accepting it.

Cheers.
/s

**Comment by mattmcdev** [comment]
Based on Taylor's most recent comments, 5.1 is probably the only LTS release Laravel will get.

https://twitter.com/taylorotwell/status/809768330118758400

**Comment by sroutier** [comment]
Well that kinda sucks.... I get the argument that LTS encourages the accumulation of a merge, update and test debt, but in an enterprise environment where stability and support is expected for periods often of over 5 years, not having a extended and predictable support timeline is a deterrent.

Either way, this does not change anything for me in the short-term, I have to concentrate on making this package work with Laravel 5.1, and I expect/hope to be able to upgrade to Laravel 5.5 shortly after it is released. 

That does not mean that upgrading to a higher and more recent release of Laravel would be hard or impossible, I would hope that it be pretty straight forward. In fact I would really appreciate if someone would try it and send me a PR. There has been a few request for it and I am sure a few others would use it.

But until then....

Cheers guys.
/s

**Comment by sroutier** [comment]
Follow up on this, just announced today Laravel 5.5 will be the next LTS.
https://twitter.com/laravelphp/status/833710294446833664

I think that this is good news, as it helps us make a case for Laravel to all our PHB.
