### ISSUE TITLE
Lesk with Laravel 5.3

### ISSUE THREAD

**Issue by nwaughachukwuma** [leskhq/Laravel-Enterprise-Starter-Kit#87]
Hey guys!

Are there plans to upgrade the Laravel version of LESK to 5.3?

**Comment by dsnoeck** [comment]
No, Laravel 5.5 LTS will be the next supported version:
See https://github.com/sroutier/laravel-enterprise-starter-kit/issues/81

**Comment by nwaughachukwuma** [comment]
Thanks @dsnoeck
