### ISSUE TITLE
The flash object

### ISSUE THREAD

**Issue by nwaughachukwuma** [leskhq/Laravel-Enterprise-Starter-Kit#88]
Hi @sroutier  and everyone,

Please where is this, **@include('flash::message')** in partials_body_content.blade.php file, called from? I have tried to trace it but I could't find it.

**Comment by sroutier** [comment]
If I understand your question properly, you are looking for the blade source that the **@include('flash::message')** loads, correct?
It is provided by the laracast/flash the originals are located under `vendor/laracasts/flash/src/views/message.blade.php` but they have been published for modification within LESK and located under `resources/views/vendor/flash/message.blade.php`.

Does that help?
/s

**Comment by nwaughachukwuma** [comment]
Thanks so much @sroutier It helped
