### ISSUE TITLE
ErrorException in EloquentLDAPUserProvider.php

### ISSUE THREAD

**Issue by dvolve** [leskhq/Laravel-Enterprise-Starter-Kit#9]
ErrorException in EloquentLDAPUserProvider.php line 167: Argument 1 passed to Sroutier\EloquentLDAP\Providers\EloquentLDAPUserProvider::validateCredentials() must be an instance of Illuminate\Contracts\Auth\Authenticatable

Standard install 
Got this after attemping login.

Good luck with the laptop dude

**Comment by dvolve** [comment]
swaylay - thanks for the response.
will check my installation of bower.

**Comment by sroutier** [comment]
Hello @dvolve, I am not getting that error at all. Did you make any progress on this issue?
Looks like @swaylay, may have sent you a PM with a tip. Did that help?

/s

**Comment by sroutier** [comment]
Hello, I hope you got it all working. I have not heard from you in a while so I will close this issue.
Shoot me a note if you have any other questions?
/s
