### ISSUE TITLE
Default domain for username registration

### ISSUE THREAD

**Issue by peteremmanuel** [leskhq/Laravel-Enterprise-Starter-Kit#90]
Hi @sroutier and everybody,

I am using this starter kit to implement a web application that's intended for use within organizations. This implies that users cannot create themselves by signing up, but are created by system admin, and can subsequently login after they are created. This is working fine. But I want admin to only create users working in the organization, and have official email addresses i.e. email addresses with companies domain name. Is there a way to configure this app, probably at config/auth.php to have a default domain for user registration, such that admin cannot register anyone outside the organization, and also such that, as an additional feature, users login with their username, and the system adds the domain name automatically?

**Comment by sroutier** [comment]
Hello @peteremmanuel,

Not sure that I fully understood your requirements and question. So let me know if you still have any questions after this answer/comment.

Users within an organization can sign-up themselves if they have an internal/company email address. Admins do not have to do all the work.

If you integrate with a central directory authority such as LDAP or MSAD users will automatically be created on the first login, additionally with the auto-magic group to role mapping feature they will be granted the permissions that have been assigned to their matching groups/roles, making user and permission management a lot easier.

Other then that there is currently no way to restrict the domain that user register from. You can prevent users from self registering and train your admin to only create internal/company accounts. That might be the easiest way to your solution.

If you want to contribute and submit a patch in a PR, it will be gladly accepted. As you mentioned it, a new setting defined in config/auth.php seems like a good location, it would also require an addition in the authentication logic to accept or deny entry into the system.

Cheers.
/S

**Comment by peteremmanuel** [comment]
Hi @sroutier I have solved the problem by adding regex option to the validation rules on app/http/request/CreateUserRequest.php file i.e. email=> 'required|unique:users|regex: (domain_regex)' That way, only users with the organization's email address can be created. 

Your suggestion is perfect, but in the system we are building, admin creates users, and users get email from which they are token-redirected to change their password. This is so because the system needs to secure a users transaction. Thanks for your timely response

**Comment by sroutier** [comment]
Cool, glad you got it working the way you need.
/s
