### ISSUE TITLE
AD ERROR: Exception retrieving user information: Array to string conversion

### ISSUE THREAD

**Issue by a-pinto** [leskhq/Laravel-Enterprise-Starter-Kit#92]
Hi, 

I'm trying to setup LESK for a project of mine where I need to use a AD for authentication. I've configured it to do so, but keep getting the following errors. I've checked for networks requests to the the AD server, but there are none.

`[2017-05-08 15:42:05] dev.ERROR: Failed to render breadcrumb trail. {"Exception":"[object] (App\\Exceptions\\MenuBuilderMenuItemNotFoundException(code: 0): Menu item [home] not found for URL [welcome]. at /Users/aap/projetos/wex/app/Handlers/LESKSecuredMenuHandler.php:185)"} 
[2017-05-08 15:42:13] dev.ERROR: Exception retrieving user information: Array to string conversion  
[2017-05-08 15:42:13] dev.ERROR: #0 /Users/aap/projetos/wex/vendor/adldap2/adldap2/src/Connections/Ldap.php(353): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Array to string...', '/Users/aap/proj...', 353, Array)
#1 /Users/aap/projetos/wex/vendor/adldap2/adldap2/src/Adldap.php(255): Adldap\Connections\Ldap->connect(Array, '389')
#2 /Users/aap/projetos/wex/vendor/adldap2/adldap2/src/Adldap.php(86): Adldap\Adldap->connect()
#3 /Users/aap/projetos/wex/vendor/sroutier/eloquent-ldap/src/Providers/EloquentLDAPUserProvider.php(452): Adldap\Adldap->__construct(Object(Adldap\Connections\Configuration))
#4 /Users/aap/projetos/wex/vendor/sroutier/eloquent-ldap/src/Providers/EloquentLDAPUserProvider.php(261): Sroutier\EloquentLDAP\Providers\EloquentLDAPUserProvider->getLDAPUserInfo('wewewewe')
#5 /Users/aap/projetos/wex/vendor/sroutier/eloquent-ldap/src/Providers/EloquentLDAPUserProvider.php(148): Sroutier\EloquentLDAP\Providers\EloquentLDAPUserProvider->createUserFromLDAP('wewewewe')
#6 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Auth/Guard.php(365): Sroutier\EloquentLDAP\Providers\EloquentLDAPUserProvider->retrieveByCredentials(Array)
#7 [internal function]: Illuminate\Auth\Guard->attempt(Array, false)
#8 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Support/Manager.php(137): call_user_func_array(Array, Array)
#9 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(217): Illuminate\Support\Manager->__call('attempt', Array)
#10 /Users/aap/projetos/wex/app/Http/Controllers/Auth/AuthController.php(92): Illuminate\Support\Facades\Facade::__callStatic('attempt', Array)
#11 [internal function]: App\Http\Controllers\Auth\AuthController->postLogin(Object(Illuminate\Http\Request))
#12 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#13 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('postLogin', Array)
#14 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Auth\AuthController), Object(Illuminate\Routing\Route), 'postLogin')
#15 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 /Users/aap/projetos/wex/app/Http/Middleware/RedirectIfAuthenticated.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 [internal function]: App\Http\Middleware\RedirectIfAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#20 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\Auth\AuthController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'postLogin')
#24 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'postLogin')
#25 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#26 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#33 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#34 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#35 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#36 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 /Users/aap/projetos/wex/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#40 /Users/aap/projetos/wex/vendor/arcanedev/settings/src/Http/Middleware/SettingsMiddleware.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Arcanedev\Settings\Http\Middleware\SettingsMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#43 /Users/aap/projetos/wex/app/Http/Middleware/WalledGarden.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: App\Http\Middleware\WalledGarden->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#46 /Users/aap/projetos/wex/app/Http/Middleware/LocaleSelector.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: App\Http\Middleware\LocaleSelector->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#49 /Users/aap/projetos/wex/app/Http/Middleware/ThemeSelector.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 [internal function]: App\Http\Middleware\ThemeSelector->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#52 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#55 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#58 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#61 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#64 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#67 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#69 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#70 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#72 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#73 /Users/aap/projetos/wex/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#74 /Users/aap/projetos/wex/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#75 /Users/aap/.composer/vendor/laravel/valet/server.php(133): require('/Users/aap/proj...')
#76 {main}  `

Can you see what I'm doing wrong?

Thank you.

**Comment by sroutier** [comment]
@a-pinto, Looks like something happened trying to connect to your AD server.
Could you post your ```.settings``` files, make sure to update the file if you edited the settings using the Web interface using the ```artisan setting:all```.
Remember to also change any username, password and even server name. But maintain the same formating. 
If you are not comfortable posting it here for the public to see, email it to me directly at ```sroutier@gmail.com```.
I will have a look and let you know if I see anything weird.

/s

**Comment by sroutier** [comment]
Closing this old issue, if this is still a problem let me know and we can chat about it.
