### ISSUE TITLE
Upgrade to laravel v5.4

### ISSUE THREAD

**Issue by ShahinSorkh** [leskhq/Laravel-Enterprise-Starter-Kit#96]

**Comment by dsnoeck** [comment]
If this is still the case for LESK, Laravel 5.5 LTS will be the next supported version:
See #81

**Comment by sroutier** [comment]
Hello, As stated by @dsnoeck, Laravel 5.5 LTS will be released shortly and I have already started working on the new version. It will take a while to upgrade everything but it is on its way.

**Comment by MikeSheward** [comment]
Hi @sroutier is there any release date for this (5.5 support)?

**Comment by sroutier** [comment]
Hello @BlitZ-UK, unfortunately, there is no ETA at this time. A lot of work has to be done to upgrade the current packages used in LESK or evaluate new replacements, we are also dependent on the work of others to upgrade to Laravel 5.5. Good progress is being made but I can't estimate yet when it will be ready. Keep an eye on the project page hopefully something usable will be published soon.
Cheers.
/S

**Comment by MikeSheward** [comment]
Ok thanks, i appreciate the update!
